# Generated by Django 2.1.1 on 2018-09-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('directory', models.FilePathField(allow_files=False, allow_folders=True, verbose_name='../')),
            ],
        ),
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date recorded')),
                ('footype', models.CharField(choices=[('VID', 'Video'), ('PIC', 'Picture')], default='PIC', max_length=3, verbose_name='type')),
                ('foocause', models.CharField(choices=[('PER', 'Periodic'), ('ALA', 'Alarm')], default='PER', max_length=3, verbose_name='cause')),
                ('filepath', models.FilePathField(verbose_name='Footage path')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootageManager.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootageManager.Location'),
        ),
    ]
