# Generated by Django 2.1.1 on 2018-09-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootageManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footage',
            name='length',
            field=models.IntegerField(blank=True, default=0, verbose_name='length'),
        ),
    ]
