# Generated by Django 2.1.1 on 2018-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootageManager', '0002_footage_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='footage',
            name='staticpath',
            field=models.CharField(default='', max_length=200, verbose_name='static_path'),
            preserve_default=False,
        ),
    ]
